
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'asp-web'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  
    - task: Docker@2
      inputs:
        containerRegistry: 'docker_AzureDevOps'
        repository: 'juyi504/azure_project'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/dotnet/aspnetcore/container/Application/aspnet-core-dotnet-core/Dockerfile'
        tags: 'beta1.1'
    - task: ArchiveFiles@2
      displayName: Compress file
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/html'
        includeRootFolder: true
        archiveType: 'tar'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
        replaceExistingArchive: true
    - task: S3Upload@1
      displayName: Publish archive file to s3 bucket
      inputs:
        awsCredentials: 'aws_AzureDevOps'
        regionName: 'us-west-1'
        bucketName: 'azure-dev-ops-ci-504'
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        globExpressions: '**'
        targetFolder: 'webService01'




