
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'asp-web'
  environmentName: 'WebServiceENV'

stages:
- stage: Build_Docker_Image_Push_to_Docker_Hub
  displayName: Build Docker Image
  jobs:  
  - job: Build_Docker_Image
    displayName: Build Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
  
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'docker_AzureDevOps'
        repository: 'juyi504/azure_project'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/dotnet/aspnetcore/container/Application/aspnet-core-dotnet-core/Dockerfile'
        tags: '$(Build.BuildId)'


- stage: archive_HTML_file
  displayName: Build
  jobs:  
  - job: Archive_Build
    displayName: Archive Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: ArchiveFiles@2
      displayName: Compress file
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/html'
        includeRootFolder: true
        archiveType: 'tar'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz'
        replaceExistingArchive: true
    - task: S3Upload@1
      displayName: Publish archive file to s3 bucket
      inputs:
        awsCredentials: 'aws_AzureDevOps'
        regionName: 'us-west-1'
        bucketName: 'azure-dev-ops-ci-504'
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        globExpressions: '**'
        targetFolder: 'webService01'

- stage: Deploy
  displayName: Deploy WebService
  dependsOn: Build_Docker_Image_Push_to_Docker_Hub
  condition: succeeded()
  jobs:
  - deployment: DeployWebService
    pool:
       vmImage: 'ubuntu-latest'
    environment: ${environmentName}
    strategy:
      runOnce:
        deploy:      
          steps:
            - task: CodeDeployDeployApplication@1
              inputs:
                awsCredentials: 'aws_AzureDevOps'
                regionName: 'us-west-1'
                applicationName: 'webService01'
                deploymentGroupName: 'webService01'
                deploymentRevisionSource: 's3'
                bucketName: 'azure-dev-ops-ci-504'
                bundleKey: 'webService01/$(Build.BuildId).tar.gz'


            
    




