version: 0.0
os: linux 
files:
  - source: webapp/Application
    destination: apache-tomcat-9.0.30/webapps/ROOT
hooks:
  BeforeInstall:
    - location: apache-tomcat-9.0.30/bin/startup.sh
      timeout: 300

